micronaut:
    application:
        name: micronaut-demo
---
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
dataSource:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''       
---
postgres:
    reactive:
        client:
          port: 5432
          host: 35.239.157.161
          database: siniestros
          user: postgres
          password: 1qwerty7
          maxSize: 5