micronaut:
    application:
        name: micronaut-seguridad
    security:
        enabled: true
        endpoints:
            login:
                enabled: true
            oauth:
                enabled: true
        token:
            jwt:
                enabled: true
                signatures:
                    secret:
                        generator:
                            secret: claveSuperUltraDuperSecretaYExtensa