micronaut:
    application:
        name: websocket-chat
    router:
        static-resources:
            default:
                enabled: true
                mapping: /**
                paths: classpath:public
jackson:
    serialization:
        indentOutput: true
        writeDatesAsTimestamps: false